name: Demo by ${{ github.actor }}
run-name: ${{ github.actor }} is testing Github Actions Demo


on:
  schedule:
    - cron: '*/5 * * * *'





jobs:
  demo-test-1:
    name: First Job ${{ github.job }}
    runs-on: ubuntu-latest
    steps:
      - name: First Step ${{ job.name }}
        uses: actions/checkout@v4
      - run: |
          echo "Hello, World! This is the first step of the demo."
          echo "This is a commit message: ${{ github.event.head_commit.message }}"
          echo "This is the SHA of the commit: ${{ github.sha }}"
          echo "This is the author of the commit: ${{ github.actor }}"
          echo "This is the repository: ${{ github.repository }}"
          echo "This is the branch: ${{ github.ref }}"
